# Generated by Django 2.2 on 2023-11-23 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_auto_20231120_1513'),
        ('app01', '0010_order_task'),
    ]

    operations = [
    ]
